### ISSUE TITLE
A question about the result of homomorphic multiplication for BFV scheme in this demo.

### ISSUE THREAD

**Issue by Z-NAVY** [Alisah-Ozcan/HE_GPU#1]
When I try to evaluate homomorphic multiplication for BFV scheme in Main.cu, I get an error result. The result shows it has only a right coefficient in first position, and the rest are zero in all. In this test, I close the INTT in GPU_Encode and the NTT in GPU_Decode. I get success when I try homomorphic addition.

I try to get the reason behind the result. Then I found the result became weird after function FORWARD_NTT_DIM_NEW_Shared_ALL.

**Comment by paul666chen** [comment]
Hi ,I wanna to build and run the main.cu but it  reported an error : segement fault. I would like to know how you compile this program，thank you !
